"""
Django settings for bernardshop project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ai*mmorki@rq(na&2+)96cocssyz1(iut+c77ac7wbzttt(61y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account.apps.AccountConfig',
    'cart.apps.CartConfig',
    'coupon.apps.CouponConfig',
    'eshop.apps.EshopConfig',
    'orders.apps.OrdersConfig',
    'payment.apps.PaymentConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bernardshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,  # Template namespacing
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processor.cart'  # When loaded, Cart instance is avilable to all templates
            ],
        },
    },
]

WSGI_APPLICATION = 'bernardshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Loading user uploaded images from a base directory using the Django developement server
# Note: possible because, DEBUG = TRUE

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Shopping cart ID for browsing sessions

CART_SESSION_ID = 'cart'

# Renders mail message to console.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Paystack test API keys
PAYSTACK_ENDPOINT: str = "https://api.paystack.co/transaction/initialize"
PAYSTACK_SK: str = "sk_test_e3efbe5c953602af5b7e544058d1d4761201a98d"
PAYSTACK_PK: str = "pk_test_33c589c93d426ead744a42658a41afdfb7183fee"

# Stripe test API keys
STRIPE_PK: str = "pk_test_51N9R3mKKp3NCphne7N8SYHF987nIgoSziytgn" \
    "n5kAH7fVsOh5GFVEG5Ph3FQ9G1Ptuo2hs1VjdKGkGpK0ULIH8oD00x0RSyj0f"
STRIPE_SK: str = "sk_test_51N9R3mKKp3NCphneOWsyoT3V8gkPof5pNdcyN7mt" \
    "wVZKueSi6TVGdw0xQZRCNtskbK2QNA2g7tPltDDfvQdZSIVQ00zDqVIEhT"
STRIPE_API_VERSION: str = "2022-11-15"
STRIPE_WEBHOOK_SECRET: str = "whsec_ce6416a64caaaae5460b9182ee7637eb27e" \
    "de9f17910359b4fa2d8b44820517a"
    